//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaComun.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion_Trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacion_Trabajo()
        {
            this.Historico_Estacion_Trabajo = new HashSet<Historico_Estacion_Trabajo>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int ID_Estado_Trabajo { get; set; }
        public int Modo_ID_Figura { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Origin_Date { get; set; }
        public System.DateTime Edit_Date { get; set; }
    
        public virtual Estado_Estacion_Trabajo Estado_Estacion_Trabajo { get; set; }
        public virtual Figura Figura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico_Estacion_Trabajo> Historico_Estacion_Trabajo { get; set; }
    }
}
