//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaComun.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int ID { get; set; }
        public int ID_Item { get; set; }
        public int ID_Evento { get; set; }
        public System.TimeSpan Tiempo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Origin_Date { get; set; }
        public System.DateTime Edit_Date { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Item Item { get; set; }
    }
}
