//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaComun.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_Estacion_Trabajo
    {
        public int ID { get; set; }
        public int ID_Estacion_Trabajo { get; set; }
        public int ID_Estado_Estacion_Trabajo { get; set; }
        public int ID_Modo { get; set; }
        public System.TimeSpan Tiempo_Estacion_Trabajo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Origin_Date { get; set; }
        public System.DateTime Edit_Date { get; set; }
    
        public virtual Estacion_Trabajo Estacion_Trabajo { get; set; }
        public virtual Estado_Estacion_Trabajo Estado_Estacion_Trabajo { get; set; }
        public virtual Figura Figura { get; set; }
    }
}
